### ISSUE TITLE
CPU 6 and 7 freeze on high speed.

### ISSUE THREAD

**Issue by Yesen777** [ProjectElixir-Devices/device_xiaomi_camellia#1]
In file init.mt6833.rc rows 394 and 395:
    chown system system /sys/devices/system/cpu/cpufreq/policy4/scaling_governor
    chmod 0660 /sys/devices/system/cpu/cpufreq/policy4/scaling_governor

But there is no policy4 folder in the phone, it is policy6. Maybe that's why the battery drains quickly.

And line 919 too...

   write /sys/devices/system/cpu/cpufreq/policy4/scaling_governor "schedplus"

**Comment by rexix01** [comment]
well, i'll try later
